// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/galogen13/gophermart-loyalty/internal/service/loyalty (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/storage_mock.go . Storage
//

// Package mock_loyalty is a generated GoMock package.
package mock_loyalty

import (
	context "context"
	reflect "reflect"

	market "github.com/galogen13/gophermart-loyalty/internal/service/market"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockStorage) AddOrder(ctx context.Context, order *market.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockStorageMockRecorder) AddOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockStorage)(nil).AddOrder), ctx, order)
}

// AddUser mocks base method.
func (m *MockStorage) AddUser(ctx context.Context, user *market.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockStorageMockRecorder) AddUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockStorage)(nil).AddUser), ctx, user)
}

// AddWithdrawalWithBalanceCheck mocks base method.
func (m *MockStorage) AddWithdrawalWithBalanceCheck(ctx context.Context, withdrawal *market.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWithdrawalWithBalanceCheck", ctx, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWithdrawalWithBalanceCheck indicates an expected call of AddWithdrawalWithBalanceCheck.
func (mr *MockStorageMockRecorder) AddWithdrawalWithBalanceCheck(ctx, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWithdrawalWithBalanceCheck", reflect.TypeOf((*MockStorage)(nil).AddWithdrawalWithBalanceCheck), ctx, withdrawal)
}

// GetBalanceByUserID mocks base method.
func (m *MockStorage) GetBalanceByUserID(ctx context.Context, user *market.User) (*market.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUserID", ctx, user)
	ret0, _ := ret[0].(*market.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUserID indicates an expected call of GetBalanceByUserID.
func (mr *MockStorageMockRecorder) GetBalanceByUserID(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUserID", reflect.TypeOf((*MockStorage)(nil).GetBalanceByUserID), ctx, user)
}

// GetOrderByNumber mocks base method.
func (m *MockStorage) GetOrderByNumber(ctx context.Context, order *market.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockStorageMockRecorder) GetOrderByNumber(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockStorage)(nil).GetOrderByNumber), ctx, order)
}

// GetOrdersByStatuses mocks base method.
func (m *MockStorage) GetOrdersByStatuses(ctx context.Context, statuses []market.OrderStatus) ([]market.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByStatuses", ctx, statuses)
	ret0, _ := ret[0].([]market.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByStatuses indicates an expected call of GetOrdersByStatuses.
func (mr *MockStorageMockRecorder) GetOrdersByStatuses(ctx, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByStatuses", reflect.TypeOf((*MockStorage)(nil).GetOrdersByStatuses), ctx, statuses)
}

// GetOrdersByUserID mocks base method.
func (m *MockStorage) GetOrdersByUserID(ctx context.Context, user *market.User) ([]market.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, user)
	ret0, _ := ret[0].([]market.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockStorageMockRecorder) GetOrdersByUserID(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockStorage)(nil).GetOrdersByUserID), ctx, user)
}

// GetUserByLogin mocks base method.
func (m *MockStorage) GetUserByLogin(ctx context.Context, user *market.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockStorageMockRecorder) GetUserByLogin(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockStorage)(nil).GetUserByLogin), ctx, user)
}

// GetWithdrawalsByUserID mocks base method.
func (m *MockStorage) GetWithdrawalsByUserID(ctx context.Context, user *market.User) ([]market.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUserID", ctx, user)
	ret0, _ := ret[0].([]market.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUserID indicates an expected call of GetWithdrawalsByUserID.
func (mr *MockStorageMockRecorder) GetWithdrawalsByUserID(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUserID", reflect.TypeOf((*MockStorage)(nil).GetWithdrawalsByUserID), ctx, user)
}

// UpdateOrderAccrual mocks base method.
func (m *MockStorage) UpdateOrderAccrual(ctx context.Context, orderAccrual market.OrderAccrual) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderAccrual", ctx, orderAccrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderAccrual indicates an expected call of UpdateOrderAccrual.
func (mr *MockStorageMockRecorder) UpdateOrderAccrual(ctx, orderAccrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderAccrual", reflect.TypeOf((*MockStorage)(nil).UpdateOrderAccrual), ctx, orderAccrual)
}
